### ISSUE TITLE
README is inadequate

### ISSUE THREAD

**Issue by DinoChiesa** [Abdul-Kinadiyil/apigee-jms#1]
The README is quite short. It's not clear what problem is being solved, or exactly how. 

Also there is no detail regarding the northbound and southbound folders, explaining what in particular is being solved by each one of them, and how.

**Comment by Abdul-Kinadiyil** [comment]
I updated the README for this repo. Let me know if you have any other comments.

**Comment by DinoChiesa** [comment]
Excellent, thank you! Very helpful.
